---
#
# download content
#
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: rpmbuild
  register: r_tempdir
- ansible.builtin.set_fact:
    f_work_dir: "{{ r_tempdir['path'] }}"
- debug:
    var: f_work_dir

- name: Git checkout
  ansible.builtin.git:
    repo: "https://{{ git_user | urlencode }}:{{ git_token | urlencode }}@{{ git_host }}/{{ git_org }}/{{ git_repo }}.git"
    dest: "{{ f_work_dir }}"


