---
#
# rpmbuild tree
#
- name: Create rpmbuild directories
  ansible.builtin.command: 
    cmd: rpmdev-setuptree


# add spec file
#
- name: Copy spec file
  ansible.builtin.copy: 
    remote_src: true 
    src: "{{ f_work_dir }}/{{ item['name'] }}/specs/{{ item['name'] }}.spec"
    dest: "{{ f_rpmbuild_dir }}/SPECS/{{ item['name'] }}.spec"
  loop: "{{ f_spec_versions }}"

- name: remove the specs dir
  ansible.builtin.file:
    path: "{{ f_work_dir }}/specs"
    state: absent


# tar up source files, gzip and dump in SOURCES
#
- name: Create archive for Source0
  community.general.archive:
    path: "{{ f_work_dir }}/{{ item['name'] }}/{{ item['name'] }}-{{ item['version'] }}"
    dest: "{{ f_rpmbuild_dir }}/SOURCES/{{ item['name'] }}-{{ item['version'] }}.tgz"
  loop: "{{ f_spec_versions }}"

