---
# build howto
# https://www.redhat.com/sysadmin/create-rpm-package
# macro reference 
# https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/
# RPM packaging user guide
# https://rpm-packaging-guide.github.io/
#
# install packages, requires elevated privilege
- name: rpmbuilder pre work
  hosts: rpmbuilder
  become: true
  gather_facts: false
  tasks:
    #- ansible.builtin.include_tasks: 
    #    file: prep.yml


- name: rpmbuilder work
  hosts: rpmbuilder
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: 
        file: "{{ tasks_file }}"
      loop: 
        # defines f_work_dir
        - download_to_tmp.yml
        # defines f_source_dir and f_spec_dir
        - build.yml
      loop_control: 
        loop_var: tasks_file


- name: rpmbuilder post work
  hosts: rpmbuilder
  become: false
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: 
        file: clean.yml

