---
# loosely based on 
# https://github.com/openvswitch/ovs/blob/master/poc/playbook-centos-builder.yml
#
- name: rpmbuilder pre work
  hosts: rpmbuilder
  become: true
  gather_facts: false
  name: Create RPM package from source 
  tasks:

  - name: Install RPM build tools
    ansible.builtin.yum: 
      update_cache: yes 
      name: 
      - yum-utils
      - rpmdevtools
      - createrepo
      - git
      state: present

  # incrementing integer for release
  #
  - name: Create Ansible local facts directory
    ansible.builtin.file: 
      path: /etc/ansible/facts.d 
      state: directory

  - name: Set release if missing
    ansible.builtin.copy:
      content: '{ "release":"1" }'
      dest: /etc/ansible/facts.d/rpmbuilder.fact
      force: false


- name: rpmbuilder work
  hosts: rpmbuilder
  gather_facts: false
  name: Create RPM package from source 
  vars:
    git_user: nickhardiman
    # Create a read-only token from https://github.com/settings/tokens?type=beta
    # No need to give more permission than an anonymous public user has?
    git_token: github_pat_1234...
    git_org: nickhardiman
    git_repo: rpmbuild-hello-world
  tasks:

  # rpmbuild tree
  #
  - name: Create directories
    ansible.builtin.command: 
      cmd: rpmdev-setuptree

  - name: Set RPM content source directory
    ansible.builtin.set_fact:
      f_source_dir: "~/rpmbuild/SOURCES"

  - name: Set RPM spec directory
    ansible.builtin.set_fact:
      f_source_dir: "~/rpmbuild/SPECS"

  # content
  #
  - name: Create temporary build directory
    ansible.builtin.tempfile:
      state: directory
      suffix: rpmbuild
    register: r_tempdir
  - ansible.builtin.set_fact:
      work_dir: r_tempdir['path']
  - debug:
      var: work_dir

  - name: Git checkout
    ansible.builtin.git:
      repo: "https://{{ git_user | urlencode }}:{{ git_token | urlencode }}@github.com/{{ git_org }}/{{ git_repo }}.git"
      dest: "{{ work_dir }}"
      #dest: "{{ f_source_dir }}"

  - name: Remove .git directory
    ansible.builtin.file:
      path: "{{ work_dir }}/.git"
      recurse: false
      #file_type: directory
      state: absent

  - name: Find other .git files
    ansible.builtin.find:
      paths: "{{ work_dir }}"
      #file_type: file
      #patterns: ".git*"
      patterns: "\.git.*"
      use_regex: true
    register: r_find
  - debug:
      var: r_find

  - name: Remove other .git files
    ansible.builtin.file:
      path: "{{ item['path'] }}"
      state: absent
    loop: "{{ r_find['files'] }}"
  
  # spec file
  #
  - name: Copy spec file
    ansible.builtin.copy: 
      remote_src: true 
      src: "{{ work_dir }}/spec/{{ git_repo }}.spec"
      dest: "{{ f_spec_dir }}/spec/{{ git_repo }}.spec"

  - name: Remove spec dir from content
    ansible.builtin.file: 
      path: "{{ work_dir }}/spec"
      state: absent



  # !!! tar up remaining files, gzip and dump in SOURCES

  
  
  - name: Update release number in spec file
    ansible.builtin.lineinfile:
      path: "{{ f_spec_dir }}/spec/{{ git_repo }}.spec"
      regexp: '^Release:'
      line: "Release: {{ ansible_local.rpmbuilder.release }}" 

  # build RPM
  #
  - name: Build Open vSwitch user space rpms
    command: rpmbuild -bb --without check rhel/openvswitch.spec
    args:
        chdir: "{{f_source_dir}}/openvswitch-{{version.stdout}}"

  - name: move the new RPM somewhere
    debug:
      msg: homedir maybe

  - name: remove the rpmbuild dir?
    debug:
      msg: why keep it


- name: rpmbuilder post work
  hosts: rpmbuilder
  become: true
  gather_facts: false
  name: Create RPM package from source
  tasks:

  - name: Increment release
    copy:
      content: '{ "release":"{{ansible_local.builder.release|int+1}}" }'
      dest: "/etc/ansible/facts.d/rpmbuilder.fact"

  - name: Copy updated spec back to github? 
    debug:
      msg: read/write token for rpmbuild dir?

  - name: Delete the cloned git repo
    ansible.builtin.file:
      path: "{{ work_dir }}"
      state: absent

