---
# build howto
# https://www.redhat.com/sysadmin/create-rpm-package
# macro reference 
# https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/
# RPM packaging user guide
# https://rpm-packaging-guide.github.io/
#
# For preparatory work, see playbook-prep.yml.
# This playbook installs packages, so it requires elevated privilege.

- name: Rpmbuilder work
  hosts: rpmbuilder
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks:
        file: "{{ tasks_file }}"
      loop:
        # defines f_work_dir and more
        - tempdir_create.yml
        # - from_git_to_tmp.yml
        # - from_tmp_to_rpmbuild.yml
        # - build_rpm.yml
        - gpg_keys.yml
        - sign_rpm.yml
        #- tempdir_delete.yml
      loop_control:
        loop_var: tasks_file
