---
# loosely based on 
# https://github.com/openvswitch/ovs/blob/master/poc/playbook-centos-builder.yml
#
- hosts: rpmbuilder pre work
  become: true
  gather_facts: false
  name: Create RPM package from source 
  tasks:

  - name: Install RPM build tools
    ansible.builtin.yum: 
      update_cache: yes 
      name: 
      - yum-utils
      - rpmdevtools
      - createrepo
      - git
      state: present

  # incrementing integer for release
  #
  - name: Create Ansible local facts directory
    ansible.builtin.file: 
      path: /etc/ansible/facts.d 
      state: directory

  - name: Set release if missing
    ansible.builtin.copy:
      content: '{ "release":"1" }'
      dest: /etc/ansible/facts.d/rpmbuilder.fact
      force: false


- hosts: rpmbuilder work
  gather_facts: false
  name: Create RPM package from source 
  vars:
    git_user: nickhardiman
    git_token: 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
    git_org: nickhardiman
    git_repo: ansible-examples
  tasks:

  # rpmbuild tree
  #
  - name: Create directories
    ansible.builtin.command: 
      cmd: rpmdev-setuptree

  - name: Set RPM content source directory
    ansible.builtin.set_fact:
      f_source_dir: "~/rpmbuild/SOURCES"

  - name: Set RPM spec directory
    ansible.builtin.set_fact:
      f_source_dir: "~/rpmbuild/SPECS"

  # content
  #
  - name: Git checkout
    ansible.builtin.git:
      repo: "https://{{ git_user | urlencode }}:{{ git_token | urlencode }}@github.com/{{ git_org }}/{{ git_repo }}.git"
      dest: "{{ f_source_dir }}"

  - name: Remove git directory
    ansible.builtin.file:
      path: "{{ f_source_dir }}/.git"
      state: absent

  - name: Remove other .git files
    ansible.builtin.find:
      paths: "{{ f_source_dir }}"
      patterns: ".git*"
    register: r_find
  - debug:
      var: r_find['files']

  - file:
      path: "{{ item['path'] }}"
      state: absent
    loop: "{{ r_find['files'] }}"

  # spec file
  #
  - name: Copy spec file
    ansible.buitin.copy: 
      remote_src: true 
      src: "{{ f_source_dir }}/spec/{{ git_repo }}.spec"
      dest: "{{ f_spec_dir }}/spec/{{ git_repo }}.spec"
If you want to move file you need to delete old file with file module

  - name: Remove spec dir from content
    ansible.builtin.file: 
      path: "{{ f_source_dir }}/spec"
      state: absent

  - name: Update release number in spec file
    ansible.builtin.lineinfile:
      path: "{{ f_spec_dir }}/spec/{{ git_repo }}.spec"
      regexp: '^Release:'
      line: "Release: {{ ansible_local.rpmbuilder.release }}" 

  # build RPM
  #
  - name: Build Open vSwitch user space rpms
    command: rpmbuild -bb --without check rhel/openvswitch.spec
    args:
        chdir: "{{f_source_dir}}/openvswitch-{{version.stdout}}"


- hosts: rpmbuilder post work
  become: true
  gather_facts: false
  name: Create RPM package from source
  tasks:

  - name: Bump up Build Number
    copy:
      content: '{ "release":"{{ansible_local.builder.release|int+1}}" }'
      dest: "/etc/ansible/facts.d/rpmbuilder.fact"

