---
# loosely based on 
# https://github.com/openvswitch/ovs/blob/master/poc/playbook-centos-builder.yml
#

- name: work_dir
  hosts: rpmbuilder
  gather_facts: false
  tasks:

  - name: Remove .git directory
    ansible.builtin.file:
      path: "{{ work_dir }}/.git"
      recurse: false
      #file_type: directory
      state: absent

  - name: Find other .git files
    ansible.builtin.find:
      paths: "{{ work_dir }}"
      #file_type: file
      #patterns: ".git*"
      patterns: 
        - '\.git.*'
      hidden: true
      use_regex: true
    register: r_find
  - debug:
      var: r_find

  - name: Remove other .git files
    ansible.builtin.file:
      path: "{{ item['path'] }}"
      state: absent
    loop: "{{ r_find['files'] }}"
  

